name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # Adjust to match your project version

      - name: Restore dependencies
        run: dotnet restore App/KpManagementSystemAPI/KpManagementSystemAPI.sln

      - name: Build
        run: dotnet build App/KpManagementSystemAPI/KpManagementSystemAPI.sln --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test App/KpManagementSystemAPI/KpManagementSystemAPI.sln --no-build --configuration Release --logger trx

  release-artifact:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Release Artifact
        run: |
          dotnet publish App/KpManagementSystemAPI/KpManagementSystemAPI.sln -c Release -o output
          zip -r release.zip output/

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kp-water-billing-release
          path: release.zip
